server:
  port: 0

spring:
  h2:
    console:
      enabled: false
  application:
    name: user-serivce
  datasource:
    url: jdbc:h2:tcp://localhost/~/ecommerce
    username: sa
    password:
    driver-class-name: org.h2.Driver

  config:
    import: optional:configserver:http://localhost:8888
    name: user

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

token:
  expiration_time: 864000000
  secret: secret-key