spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ecommer
    username: sa
    password: '{cipher}a631dee525184bf65c7ea8aa255e1cb264494775c3617df27cd0df0ccaeba45c'
    driver-class-name: org.h2.Driver

token:
  expiration_time: 764000000
  secret: user_token_new_#1

gateway:
    ip: 192.168.0.8