server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tg1218/spring-cloud-ecommerce.git
          search-paths: config

